[theme]
primaryColor = "#1E3A8A"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#E5E7EB"
textColor = "#1F2937"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 200
